{"name": "Verify created order is displayed in 'In Process' section", "status": "failed", "statusDetails": {"message": "Failed: User creation failed, 'accessToken' not found in response.", "trace": "@pytest.fixture(scope='function')\n    def get_new_user():\n        new_user_creds = NewUserCredentials.generate_credentials_set()\n        new_user_response = User.create_user(new_user_creds)\n        if 'accessToken' not in new_user_response.json():\n>           pytest.fail(\"User creation failed, 'accessToken' not found in response.\")\nE           Failed: User creation failed, 'accessToken' not found in response.\n\nconftest.py:41: Failed"}, "parameters": [{"name": "get_driver", "value": "'chrome'"}], "start": 1728085848681, "stop": 1728085848681, "uuid": "47dfb4ee-5f09-44e6-a730-b9eae471b9b9", "historyId": "ace771f2e513b71ce79eaf015d08ff9f", "testCaseId": "25e08268aa095e19d162f817d643ad8c", "fullName": "tests.test_order_page.TestOrderFeed#test_check_order_in_progress", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_page"}, {"name": "subSuite", "value": "TestOrderFeed"}, {"name": "host", "value": "mac.lan"}, {"name": "thread", "value": "78077-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_page"}]}